<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-08-06T02:40:47Z" name="Default suite" finished-at="2019-08-06T02:40:50Z" duration-ms="3056">
    <groups>
    </groups>
    <test started-at="2019-08-06T02:40:47Z" name="Default test" finished-at="2019-08-06T02:40:50Z" duration-ms="3056">
      <class name="com.rapidapi.rapidapitests.AvailableCurrenciesTest">
        <test-method signature="authenticateResponse()[pri:0, instance:com.rapidapi.rapidapitests.AvailableCurrenciesTest@7e6f74c]" started-at="2019-08-05T22:40:47Z" name="authenticateResponse" finished-at="2019-08-05T22:40:49Z" duration-ms="2654" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authenticateResponse -->
        <test-method signature="authenticationHappyPath()[pri:0, instance:com.rapidapi.rapidapitests.AvailableCurrenciesTest@7e6f74c]" started-at="2019-08-05T22:40:49Z" name="authenticationHappyPath" finished-at="2019-08-05T22:40:49Z" duration-ms="121" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.rapidapi.rapidapitests.AvailableCurrenciesTest.authenticationHappyPath(AvailableCurrenciesTest.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authenticationHappyPath -->
        <test-method signature="authenticationInvalidHost()[pri:0, instance:com.rapidapi.rapidapitests.AvailableCurrenciesTest@7e6f74c]" started-at="2019-08-05T22:40:49Z" name="authenticationInvalidHost" finished-at="2019-08-05T22:40:50Z" duration-ms="122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authenticationInvalidHost -->
        <test-method signature="authenticationInvalidKey()[pri:0, instance:com.rapidapi.rapidapitests.AvailableCurrenciesTest@7e6f74c]" started-at="2019-08-05T22:40:50Z" name="authenticationInvalidKey" finished-at="2019-08-05T22:40:50Z" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authenticationInvalidKey -->
      </class> <!-- com.rapidapi.rapidapitests.AvailableCurrenciesTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
